"""Multi-language support — EN (default) / TR / DE / ES / FR / RU / ZH / PT / JA / AR"""

LANG = "en"  # default

STRINGS = {
    "en": {
        # Banner
        "banner_title": "WordPress Password Tester",
        "banner_auth": "Authorized Use Only",

        # Headers
        "config": "CONFIGURATION",
        "phase1": "PHASE 1: RECONNAISSANCE",
        "phase2": "PHASE 2: STRATEGY",
        "phase3": "PHASE 3: WORDLIST",
        "phase4": "PHASE 4: ATTACK",
        "phase5": "PHASE 5: REPORT",
        "found_header": "CREDENTIALS FOUND",

        # Interactive
        "target_url": "Target URL",
        "usernames": "Usernames (comma separated, empty=auto discover)",
        "company_name": "Company name (for wordlist, empty=skip)",
        "extra_keywords": "Extra keywords (comma separated, empty=skip)",
        "crawl_site": "Crawl site for words?",
        "extra_wordlist": "Extra wordlist file (empty=skip)",
        "proxy_file": "Proxy list file (empty=skip)",
        "output_dir": "Output directory",
        "start_confirm": "Start attack?",
        "cancelled": "Cancelled.",
        "url_required": "URL is required!",

        # Method select
        "method_title": "Attack method",
        "method_auto": "auto    — Automatically select best method (recommended)",
        "method_xmlrpc": "xmlrpc  — XML-RPC multicall (fast, bulk testing, ideal without WAF)",
        "method_wplogin": "wplogin — wp-login.php POST (slow but reliable, works everywhere)",
        "method_restapi": "restapi — REST API Basic Auth (slow, requires Application Passwords)",

        # Batch select
        "batch_title": "Batch size (passwords per request)",
        "batch_10": "10  — Very slow but safe, low ban risk on WAF sites",
        "batch_25": "25  — Balanced, medium speed, suitable for most sites",
        "batch_50": "50  — Fast, recommended for sites without WAF (default)",
        "batch_100": "100 — Very fast but risky, noticeable in server logs",
        "batch_200": "200 — Aggressive, high ban risk, use only with proxies",

        # Delay select
        "delay_title": "Delay between requests",
        "delay_05": "0.5s — Very fast, very high ban risk, proxy only",
        "delay_1": "1s   — Fast, usable on sites without WAF",
        "delay_2": "2s   — Balanced, suitable for most sites",
        "delay_3": "3s   — Safe, recommended for WAF sites (default)",
        "delay_5": "5s   — Very safe, slow but almost zero ban risk",
        "delay_10": "10s  — Ultra safe, takes long but completely undetectable",

        # Risk
        "risk_high": "High risk profile — high chance of getting banned!",
        "risk_high_tip": "Tip: add proxy list or increase delay",
        "risk_medium": "Medium risk profile — proceed carefully",
        "risk_low": "Low risk profile — safe settings",
        "risk_label": "Risk",

        # Stats table
        "stat_target": "Target",
        "stat_user": "Username",
        "stat_company": "Company",
        "stat_method": "Method",
        "stat_batch": "Batch",
        "stat_delay": "Delay",
        "stat_proxy": "Proxy",
        "stat_pwd_per_req": "pwd/req",
        "stat_none": "none",
        "stat_auto": "auto discover",

        # Scanner
        "scanning": "Scanning target...",
        "scan_wp": "WordPress",
        "scan_login": "Login URL",
        "scan_xmlrpc": "XML-RPC",
        "scan_captcha": "CAPTCHA",
        "scan_waf": "WAF",
        "scan_users": "Users",
        "scan_plugins": "Plugins",
        "scan_active": "ACTIVE",
        "scan_methods": "methods",
        "scan_disabled": "DISABLED",
        "scan_yes": "YES",
        "scan_no": "NO",
        "scan_not_found": "not found",
        "scan_new_user": "New user discovered",

        # Wordlist
        "generating": "Generating passwords...",
        "generated": "passwords generated",
        "users_label": "Users",

        # Attack
        "all_tried": "All passwords already tried",
        "passwords": "passwords",
        "batches": "batches",
        "candidate": "Candidate",
        "verifying": "verifying...",
        "false_positive": "False positive",
        "not_found": "not found",
        "attempts": "attempts",
        "banned_proxy": "Switching proxy",
        "remaining": "remaining",
        "all_proxies_banned": "All proxies banned!",
        "ip_banned": "IP BANNED! Change VPN and use --resume to continue",
        "connection_lost": "Connection lost",
        "waiting": "waiting",
        "ban_detected": "Ban detected",

        # Report
        "total_tried": "Total tried",
        "total_generated": "Total generated",
        "found_count": "Found",
        "http_requests": "HTTP requests",
        "blocks": "Blocks",
        "ban_count": "Ban count",
        "no_password": "No password found — but unblocked attack is itself a vulnerability",
        "report_at": "Report",
        "log_at": "Log",

        # Found
        "password_found": "PASSWORD FOUND!",
        "no_user": "No username found! Use -U to specify.",

        # Risk labels
        "risk_low_label": "low",
        "risk_medium_label": "medium",
        "risk_high_label": "high",

        # Language selection
        "lang_select": "Language / Dil",
        "lang_en": "English",
        "lang_tr": "Türkçe",

        # Strategy
        "strategy_xmlrpc": "XML-RPC multicall — fastest method",
        "strategy_wplogin": "wp-login.php POST",
        "strategy_restapi": "REST API Basic Auth",
        "strategy_captcha_switch": "CAPTCHA detected! Switching to XML-RPC",

        # Report table headers
        "report_user": "User",
        "report_password": "Password",
        "report_time": "Time",
        "report_title": "WordPress Brute Force Report",
        "report_date": "Date",

        # Ctrl+C / Shutdown
        "interrupted": "Interrupted by user (Ctrl+C)",
        "state_saved": "Progress saved. Use --resume to continue.",
        "report_saved": "Report saved.",
        "resume_hint": "Run again with --resume to continue from where you left off.",

        # ETA
        "total_time": "Total time",

        # Dry run
        "dry_run_header": "DRY RUN — WORDLIST ONLY",
        "dry_run_saved": "Wordlist saved to",

        # Max passwords
        "max_passwords": "Max passwords (0=unlimited)",
        "stat_max": "Max limit",
        "stat_unlimited": "unlimited",

        # Found behavior
        "found_skip": "Skipping remaining users",
        "stop_on_found": "Stop after first password found?",

        # Misc
        "scan_start": "Scanning target...",
    },

    "tr": {
        # Banner
        "banner_title": "WordPress Şifre Test Aracı",
        "banner_auth": "Yalnızca Yetkili Kullanım",

        # Headers
        "config": "YAPILANDIRMA",
        "phase1": "FAZ 1: KEŞİF",
        "phase2": "FAZ 2: STRATEJİ",
        "phase3": "FAZ 3: WORDLIST",
        "phase4": "FAZ 4: SALDIRI",
        "phase5": "FAZ 5: RAPOR",
        "found_header": "BULUNAN ŞİFRELER",

        # Interactive
        "target_url": "Hedef URL",
        "usernames": "Kullanıcı adları (virgülle, boş=otomatik keşfet)",
        "company_name": "Firma adı (wordlist için, boş=atla)",
        "extra_keywords": "Ek anahtar kelimeler (virgülle, boş=atla)",
        "crawl_site": "Siteden kelime çek?",
        "extra_wordlist": "Ek wordlist dosyası (boş=atla)",
        "proxy_file": "Proxy listesi dosyası (boş=atla)",
        "output_dir": "Çıktı dizini",
        "start_confirm": "Başlatılsın mı?",
        "cancelled": "İptal edildi.",
        "url_required": "URL gerekli!",

        # Method select
        "method_title": "Saldırı yöntemi",
        "method_auto": "auto    — Otomatik en iyi yöntemi seç (önerilen)",
        "method_xmlrpc": "xmlrpc  — XML-RPC multicall (hızlı, toplu deneme, WAF yoksa ideal)",
        "method_wplogin": "wplogin — wp-login.php POST (yavaş ama güvenilir, her sitede çalışır)",
        "method_restapi": "restapi — REST API Basic Auth (yavaş, Application Passwords gerekli)",

        # Batch select
        "batch_title": "Batch boyutu (tek istekte kaç şifre)",
        "batch_10": "10  — Çok yavaş ama güvenli, WAF olan sitelerde ban riski düşük",
        "batch_25": "25  — Dengeli, orta hızda, çoğu site için uygun",
        "batch_50": "50  — Hızlı, WAF olmayan sitelerde önerilen (varsayılan)",
        "batch_100": "100 — Çok hızlı ama riskli, sunucu log'larında dikkat çeker",
        "batch_200": "200 — Agresif, ban riski yüksek, sadece proxy ile kullan",

        # Delay select
        "delay_title": "İstekler arası bekleme",
        "delay_05": "0.5s — Çok hızlı, ban riski çok yüksek, sadece proxy ile",
        "delay_1": "1s   — Hızlı, WAF olmayan sitelerde kullanılabilir",
        "delay_2": "2s   — Dengeli, çoğu site için uygun",
        "delay_3": "3s   — Güvenli, WAF olan sitelerde önerilen (varsayılan)",
        "delay_5": "5s   — Çok güvenli, yavaş ama ban riski neredeyse sıfır",
        "delay_10": "10s  — Ultra güvenli, uzun sürer ama kesinlikle tespit edilmez",

        # Risk
        "risk_high": "Yüksek risk profili — ban yeme ihtimali yüksek!",
        "risk_high_tip": "Öneri: proxy listesi ekle veya delay'i artır",
        "risk_medium": "Orta risk profili — dikkatli devam edin",
        "risk_low": "Düşük risk profili — güvenli ayarlar",
        "risk_label": "Risk",

        # Stats table
        "stat_target": "Hedef",
        "stat_user": "Kullanıcı",
        "stat_company": "Firma",
        "stat_method": "Yöntem",
        "stat_batch": "Batch",
        "stat_delay": "Delay",
        "stat_proxy": "Proxy",
        "stat_pwd_per_req": "şifre/istek",
        "stat_none": "yok",
        "stat_auto": "otomatik keşif",

        # Scanner
        "scanning": "Hedef taranıyor...",
        "scan_wp": "WordPress",
        "scan_login": "Login URL",
        "scan_xmlrpc": "XML-RPC",
        "scan_captcha": "CAPTCHA",
        "scan_waf": "WAF",
        "scan_users": "Kullanıcılar",
        "scan_plugins": "Eklentiler",
        "scan_active": "AKTİF",
        "scan_methods": "method",
        "scan_disabled": "KAPALI",
        "scan_yes": "VAR",
        "scan_no": "YOK",
        "scan_not_found": "bulunamadı",
        "scan_new_user": "Yeni kullanıcı keşfedildi",

        # Wordlist
        "generating": "Şifreler üretiliyor...",
        "generated": "şifre üretildi",
        "users_label": "Kullanıcılar",

        # Attack
        "all_tried": "Tüm şifreler zaten denenmiş",
        "passwords": "şifre",
        "batches": "paket",
        "candidate": "Aday",
        "verifying": "doğrulanıyor...",
        "false_positive": "False positive",
        "not_found": "bulunamadı",
        "attempts": "deneme",
        "banned_proxy": "Proxy değiştiriliyor",
        "remaining": "kaldı",
        "all_proxies_banned": "Tüm proxy'ler banlandı!",
        "ip_banned": "IP BANLANDI! VPN değiştirip --resume ile devam edin",
        "connection_lost": "Bağlantı kesildi",
        "waiting": "bekleniyor",
        "ban_detected": "Ban algılandı",

        # Report
        "total_tried": "Toplam denenen",
        "total_generated": "Toplam üretilen",
        "found_count": "Bulunan",
        "http_requests": "HTTP istek",
        "blocks": "Engellenme",
        "ban_count": "Ban sayısı",
        "no_password": "Şifre bulunamadı — saldırının engellenmemesi başlı başına bir açık",
        "report_at": "Rapor",
        "log_at": "Log",

        # Found
        "password_found": "ŞİFRE BULUNDU!",
        "no_user": "Kullanıcı adı bulunamadı! -U ile belirtin.",

        # Risk labels
        "risk_low_label": "düşük",
        "risk_medium_label": "orta",
        "risk_high_label": "yüksek",

        # Language selection
        "lang_select": "Language / Dil",
        "lang_en": "English",
        "lang_tr": "Türkçe",

        # Strategy
        "strategy_xmlrpc": "XML-RPC multicall — en hızlı yöntem",
        "strategy_wplogin": "wp-login.php POST",
        "strategy_restapi": "REST API Basic Auth",
        "strategy_captcha_switch": "CAPTCHA tespit edildi! XML-RPC'ye geçiliyor",

        # Report table headers
        "report_user": "Kullanıcı",
        "report_password": "Şifre",
        "report_time": "Zaman",
        "report_title": "WordPress Brute Force Raporu",
        "report_date": "Tarih",

        # Ctrl+C / Shutdown
        "interrupted": "Kullanıcı tarafından durduruldu (Ctrl+C)",
        "state_saved": "İlerleme kaydedildi. Devam etmek için --resume kullanın.",
        "report_saved": "Rapor kaydedildi.",
        "resume_hint": "Kaldığınız yerden devam etmek için --resume ile tekrar çalıştırın.",

        # ETA
        "total_time": "Toplam süre",

        # Dry run
        "dry_run_header": "DRY RUN — SADECE WORDLIST",
        "dry_run_saved": "Wordlist kaydedildi",

        # Max passwords
        "max_passwords": "Maksimum şifre (0=sınırsız)",
        "stat_max": "Maks limit",
        "stat_unlimited": "sınırsız",

        # Found behavior
        "found_skip": "Kalan kullanıcılar atlanıyor",
        "stop_on_found": "İlk şifre bulununca dur?",

        # Misc
        "scan_start": "Hedef taranıyor...",
    },

    "de": {
        "banner_title": "WordPress Passwort-Tester", "banner_auth": "Nur autorisierte Nutzung",
        "config": "KONFIGURATION", "phase1": "PHASE 1: AUFKLARUNG", "phase2": "PHASE 2: STRATEGIE",
        "phase3": "PHASE 3: WORTLISTE", "phase4": "PHASE 4: ANGRIFF", "phase5": "PHASE 5: BERICHT",
        "found_header": "GEFUNDENE PASSWORTER",
        "target_url": "Ziel-URL", "usernames": "Benutzernamen (kommagetrennt, leer=automatisch)",
        "company_name": "Firmenname (fuer Wortliste, leer=ueberspringen)",
        "extra_keywords": "Zusaetzliche Schluesselwoerter (kommagetrennt, leer=ueberspringen)",
        "crawl_site": "Website nach Woertern durchsuchen?",
        "extra_wordlist": "Zusaetzliche Wortliste (leer=ueberspringen)",
        "proxy_file": "Proxy-Liste Datei (leer=ueberspringen)", "output_dir": "Ausgabeverzeichnis",
        "start_confirm": "Angriff starten?", "cancelled": "Abgebrochen.", "url_required": "URL ist erforderlich!",
        "method_title": "Angriffsmethode",
        "method_auto": "auto    — Automatisch beste Methode waehlen (empfohlen)",
        "method_xmlrpc": "xmlrpc  — XML-RPC Multicall (schnell, Massentest, ideal ohne WAF)",
        "method_wplogin": "wplogin — wp-login.php POST (langsam aber zuverlaessig)",
        "method_restapi": "restapi — REST API Basic Auth (langsam, erfordert Application Passwords)",
        "batch_title": "Batch-Groesse (Passwoerter pro Anfrage)",
        "batch_10": "10  — Sehr langsam aber sicher, geringes Ban-Risiko",
        "batch_25": "25  — Ausgewogen, mittlere Geschwindigkeit",
        "batch_50": "50  — Schnell, empfohlen ohne WAF (Standard)",
        "batch_100": "100 — Sehr schnell aber riskant",
        "batch_200": "200 — Aggressiv, hohes Ban-Risiko, nur mit Proxy",
        "delay_title": "Verzoegerung zwischen Anfragen",
        "delay_05": "0.5s — Sehr schnell, sehr hohes Ban-Risiko",
        "delay_1": "1s   — Schnell, nutzbar ohne WAF",
        "delay_2": "2s   — Ausgewogen, fuer die meisten Seiten",
        "delay_3": "3s   — Sicher, empfohlen mit WAF (Standard)",
        "delay_5": "5s   — Sehr sicher, langsam",
        "delay_10": "10s  — Ultra sicher, sehr langsam",
        "risk_high": "Hohes Risikoprofil — hohe Ban-Wahrscheinlichkeit!",
        "risk_high_tip": "Tipp: Proxy-Liste hinzufuegen oder Verzoegerung erhoehen",
        "risk_medium": "Mittleres Risikoprofil — vorsichtig fortfahren",
        "risk_low": "Niedriges Risikoprofil — sichere Einstellungen",
        "risk_label": "Risiko", "risk_low_label": "niedrig", "risk_medium_label": "mittel", "risk_high_label": "hoch",
        "stat_target": "Ziel", "stat_user": "Benutzer", "stat_company": "Firma", "stat_method": "Methode",
        "stat_batch": "Batch", "stat_delay": "Delay", "stat_proxy": "Proxy",
        "stat_pwd_per_req": "Pwd/Req", "stat_none": "keine", "stat_auto": "automatisch",
        "scanning": "Ziel wird gescannt...", "scan_wp": "WordPress", "scan_login": "Login URL",
        "scan_xmlrpc": "XML-RPC", "scan_captcha": "CAPTCHA", "scan_waf": "WAF",
        "scan_users": "Benutzer", "scan_plugins": "Plugins",
        "scan_active": "AKTIV", "scan_methods": "Methoden", "scan_disabled": "DEAKTIVIERT",
        "scan_yes": "JA", "scan_no": "NEIN", "scan_not_found": "nicht gefunden",
        "scan_new_user": "Neuer Benutzer entdeckt",
        "generating": "Passwoerter werden generiert...", "generated": "Passwoerter generiert",
        "users_label": "Benutzer",
        "all_tried": "Alle Passwoerter bereits getestet", "passwords": "Passwoerter", "batches": "Batches",
        "candidate": "Kandidat", "verifying": "wird ueberprueft...", "false_positive": "Falsch positiv",
        "not_found": "nicht gefunden", "attempts": "Versuche",
        "banned_proxy": "Proxy wird gewechselt", "remaining": "uebrig",
        "all_proxies_banned": "Alle Proxys gesperrt!", "ip_banned": "IP GESPERRT! VPN wechseln und --resume verwenden",
        "connection_lost": "Verbindung verloren", "waiting": "warte", "ban_detected": "Sperre erkannt",
        "total_tried": "Gesamt getestet", "total_generated": "Gesamt generiert", "found_count": "Gefunden",
        "http_requests": "HTTP-Anfragen", "blocks": "Blockierungen", "ban_count": "Sperren",
        "no_password": "Kein Passwort gefunden — aber unblockierter Angriff ist eine Schwachstelle",
        "report_at": "Bericht", "log_at": "Log",
        "password_found": "PASSWORT GEFUNDEN!", "no_user": "Kein Benutzername gefunden! -U verwenden.",
        "lang_select": "Language / Sprache", "lang_en": "English", "lang_tr": "Türkçe",
        "strategy_xmlrpc": "XML-RPC Multicall — schnellste Methode",
        "strategy_wplogin": "wp-login.php POST", "strategy_restapi": "REST API Basic Auth",
        "strategy_captcha_switch": "CAPTCHA erkannt! Wechsel zu XML-RPC",
        "report_user": "Benutzer", "report_password": "Passwort", "report_time": "Zeit",
        "report_title": "WordPress Brute-Force-Bericht", "report_date": "Datum",
        "interrupted": "Vom Benutzer unterbrochen (Ctrl+C)",
        "state_saved": "Fortschritt gespeichert. --resume zum Fortfahren.",
        "report_saved": "Bericht gespeichert.",
        "resume_hint": "Mit --resume erneut ausfuehren um fortzufahren.",
        "total_time": "Gesamtzeit",
        "dry_run_header": "DRY RUN — NUR WORTLISTE", "dry_run_saved": "Wortliste gespeichert",
        "max_passwords": "Max Passwoerter (0=unbegrenzt)", "stat_max": "Max Limit", "stat_unlimited": "unbegrenzt",
        "found_skip": "Verbleibende Benutzer uebersprungen",
    },

    "es": {
        "banner_title": "Probador de Contrasenas WordPress", "banner_auth": "Solo Uso Autorizado",
        "config": "CONFIGURACION", "phase1": "FASE 1: RECONOCIMIENTO", "phase2": "FASE 2: ESTRATEGIA",
        "phase3": "FASE 3: DICCIONARIO", "phase4": "FASE 4: ATAQUE", "phase5": "FASE 5: INFORME",
        "found_header": "CONTRASENAS ENCONTRADAS",
        "target_url": "URL objetivo", "usernames": "Usuarios (separados por comas, vacio=auto)",
        "company_name": "Nombre de empresa (para diccionario, vacio=omitir)",
        "extra_keywords": "Palabras clave adicionales (separadas por comas, vacio=omitir)",
        "crawl_site": "Extraer palabras del sitio?",
        "extra_wordlist": "Archivo de diccionario adicional (vacio=omitir)",
        "proxy_file": "Archivo de lista de proxies (vacio=omitir)", "output_dir": "Directorio de salida",
        "start_confirm": "Iniciar ataque?", "cancelled": "Cancelado.", "url_required": "URL es requerida!",
        "method_title": "Metodo de ataque",
        "method_auto": "auto    — Seleccionar mejor metodo automaticamente (recomendado)",
        "method_xmlrpc": "xmlrpc  — XML-RPC multicall (rapido, prueba masiva, ideal sin WAF)",
        "method_wplogin": "wplogin — wp-login.php POST (lento pero confiable)",
        "method_restapi": "restapi — REST API Basic Auth (lento, requiere Application Passwords)",
        "batch_title": "Tamano de lote (contrasenas por solicitud)",
        "batch_10": "10  — Muy lento pero seguro", "batch_25": "25  — Equilibrado",
        "batch_50": "50  — Rapido, recomendado sin WAF (predeterminado)",
        "batch_100": "100 — Muy rapido pero arriesgado", "batch_200": "200 — Agresivo, solo con proxy",
        "delay_title": "Retraso entre solicitudes",
        "delay_05": "0.5s — Muy rapido, riesgo muy alto", "delay_1": "1s   — Rapido",
        "delay_2": "2s   — Equilibrado", "delay_3": "3s   — Seguro (predeterminado)",
        "delay_5": "5s   — Muy seguro", "delay_10": "10s  — Ultra seguro",
        "risk_high": "Perfil de riesgo alto — alta probabilidad de bloqueo!",
        "risk_high_tip": "Consejo: agregar proxies o aumentar el retraso",
        "risk_medium": "Perfil de riesgo medio", "risk_low": "Perfil de riesgo bajo",
        "risk_label": "Riesgo", "risk_low_label": "bajo", "risk_medium_label": "medio", "risk_high_label": "alto",
        "stat_target": "Objetivo", "stat_user": "Usuario", "stat_company": "Empresa", "stat_method": "Metodo",
        "stat_batch": "Lote", "stat_delay": "Retraso", "stat_proxy": "Proxy",
        "stat_pwd_per_req": "pwd/req", "stat_none": "ninguno", "stat_auto": "descubrimiento auto",
        "scanning": "Escaneando objetivo...", "scan_wp": "WordPress", "scan_login": "URL de Login",
        "scan_xmlrpc": "XML-RPC", "scan_captcha": "CAPTCHA", "scan_waf": "WAF",
        "scan_users": "Usuarios", "scan_plugins": "Plugins",
        "scan_active": "ACTIVO", "scan_methods": "metodos", "scan_disabled": "DESACTIVADO",
        "scan_yes": "SI", "scan_no": "NO", "scan_not_found": "no encontrado",
        "scan_new_user": "Nuevo usuario descubierto",
        "generating": "Generando contrasenas...", "generated": "contrasenas generadas",
        "users_label": "Usuarios",
        "all_tried": "Todas las contrasenas ya probadas", "passwords": "contrasenas", "batches": "lotes",
        "candidate": "Candidato", "verifying": "verificando...", "false_positive": "Falso positivo",
        "not_found": "no encontrado", "attempts": "intentos",
        "banned_proxy": "Cambiando proxy", "remaining": "restantes",
        "all_proxies_banned": "Todos los proxies bloqueados!",
        "ip_banned": "IP BLOQUEADA! Cambiar VPN y usar --resume",
        "connection_lost": "Conexion perdida", "waiting": "esperando", "ban_detected": "Bloqueo detectado",
        "total_tried": "Total probados", "total_generated": "Total generados", "found_count": "Encontrados",
        "http_requests": "Solicitudes HTTP", "blocks": "Bloqueos", "ban_count": "Baneos",
        "no_password": "Contrasena no encontrada — pero ataque sin bloqueo es una vulnerabilidad",
        "report_at": "Informe", "log_at": "Log",
        "password_found": "CONTRASENA ENCONTRADA!", "no_user": "Usuario no encontrado! Usar -U.",
        "lang_select": "Language / Idioma", "lang_en": "English", "lang_tr": "Türkçe",
        "strategy_xmlrpc": "XML-RPC multicall — metodo mas rapido",
        "strategy_wplogin": "wp-login.php POST", "strategy_restapi": "REST API Basic Auth",
        "strategy_captcha_switch": "CAPTCHA detectado! Cambiando a XML-RPC",
        "report_user": "Usuario", "report_password": "Contrasena", "report_time": "Hora",
        "report_title": "Informe de Fuerza Bruta WordPress", "report_date": "Fecha",
        "interrupted": "Interrumpido por el usuario (Ctrl+C)",
        "state_saved": "Progreso guardado. Usar --resume para continuar.",
        "report_saved": "Informe guardado.",
        "resume_hint": "Ejecutar de nuevo con --resume para continuar.",
        "total_time": "Tiempo total",
        "dry_run_header": "DRY RUN — SOLO DICCIONARIO", "dry_run_saved": "Diccionario guardado",
        "max_passwords": "Max contrasenas (0=ilimitado)", "stat_max": "Limite max", "stat_unlimited": "ilimitado",
        "found_skip": "Omitiendo usuarios restantes",
    },

    "fr": {
        "banner_title": "Testeur de Mots de Passe WordPress", "banner_auth": "Usage Autorise Uniquement",
        "config": "CONFIGURATION", "phase1": "PHASE 1: RECONNAISSANCE", "phase2": "PHASE 2: STRATEGIE",
        "phase3": "PHASE 3: DICTIONNAIRE", "phase4": "PHASE 4: ATTAQUE", "phase5": "PHASE 5: RAPPORT",
        "found_header": "MOTS DE PASSE TROUVES",
        "target_url": "URL cible", "usernames": "Noms d'utilisateur (separes par virgules, vide=auto)",
        "company_name": "Nom d'entreprise (pour dictionnaire, vide=ignorer)",
        "extra_keywords": "Mots-cles supplementaires (separes par virgules, vide=ignorer)",
        "crawl_site": "Explorer le site pour des mots?",
        "extra_wordlist": "Fichier dictionnaire supplementaire (vide=ignorer)",
        "proxy_file": "Fichier liste de proxies (vide=ignorer)", "output_dir": "Repertoire de sortie",
        "start_confirm": "Lancer l'attaque?", "cancelled": "Annule.", "url_required": "URL requise!",
        "method_title": "Methode d'attaque",
        "method_auto": "auto    — Selection automatique de la meilleure methode (recommande)",
        "method_xmlrpc": "xmlrpc  — XML-RPC multicall (rapide, test en masse, ideal sans WAF)",
        "method_wplogin": "wplogin — wp-login.php POST (lent mais fiable)",
        "method_restapi": "restapi — REST API Basic Auth (lent, necessite Application Passwords)",
        "batch_title": "Taille du lot (mots de passe par requete)",
        "batch_10": "10  — Tres lent mais sur", "batch_25": "25  — Equilibre",
        "batch_50": "50  — Rapide, recommande sans WAF (defaut)",
        "batch_100": "100 — Tres rapide mais risque", "batch_200": "200 — Agressif, proxy uniquement",
        "delay_title": "Delai entre les requetes",
        "delay_05": "0.5s — Tres rapide, risque tres eleve", "delay_1": "1s   — Rapide",
        "delay_2": "2s   — Equilibre", "delay_3": "3s   — Sur (defaut)",
        "delay_5": "5s   — Tres sur", "delay_10": "10s  — Ultra sur",
        "risk_high": "Profil a haut risque — forte probabilite de bannissement!",
        "risk_high_tip": "Conseil: ajouter des proxies ou augmenter le delai",
        "risk_medium": "Profil a risque moyen", "risk_low": "Profil a faible risque",
        "risk_label": "Risque", "risk_low_label": "faible", "risk_medium_label": "moyen", "risk_high_label": "eleve",
        "stat_target": "Cible", "stat_user": "Utilisateur", "stat_company": "Entreprise", "stat_method": "Methode",
        "stat_batch": "Lot", "stat_delay": "Delai", "stat_proxy": "Proxy",
        "stat_pwd_per_req": "mdp/req", "stat_none": "aucun", "stat_auto": "decouverte auto",
        "scanning": "Scan de la cible...", "scan_wp": "WordPress", "scan_login": "URL de connexion",
        "scan_xmlrpc": "XML-RPC", "scan_captcha": "CAPTCHA", "scan_waf": "WAF",
        "scan_users": "Utilisateurs", "scan_plugins": "Extensions",
        "scan_active": "ACTIF", "scan_methods": "methodes", "scan_disabled": "DESACTIVE",
        "scan_yes": "OUI", "scan_no": "NON", "scan_not_found": "non trouve",
        "scan_new_user": "Nouvel utilisateur decouvert",
        "generating": "Generation des mots de passe...", "generated": "mots de passe generes",
        "users_label": "Utilisateurs",
        "all_tried": "Tous les mots de passe deja testes", "passwords": "mots de passe", "batches": "lots",
        "candidate": "Candidat", "verifying": "verification...", "false_positive": "Faux positif",
        "not_found": "non trouve", "attempts": "tentatives",
        "banned_proxy": "Changement de proxy", "remaining": "restants",
        "all_proxies_banned": "Tous les proxies bannis!",
        "ip_banned": "IP BANNIE! Changer VPN et utiliser --resume",
        "connection_lost": "Connexion perdue", "waiting": "attente", "ban_detected": "Ban detecte",
        "total_tried": "Total testes", "total_generated": "Total generes", "found_count": "Trouves",
        "http_requests": "Requetes HTTP", "blocks": "Blocages", "ban_count": "Bannissements",
        "no_password": "Mot de passe non trouve — mais une attaque non bloquee est une vulnerabilite",
        "report_at": "Rapport", "log_at": "Log",
        "password_found": "MOT DE PASSE TROUVE!", "no_user": "Aucun utilisateur trouve! Utiliser -U.",
        "lang_select": "Language / Langue", "lang_en": "English", "lang_tr": "Türkçe",
        "strategy_xmlrpc": "XML-RPC multicall — methode la plus rapide",
        "strategy_wplogin": "wp-login.php POST", "strategy_restapi": "REST API Basic Auth",
        "strategy_captcha_switch": "CAPTCHA detecte! Passage a XML-RPC",
        "report_user": "Utilisateur", "report_password": "Mot de passe", "report_time": "Heure",
        "report_title": "Rapport de Force Brute WordPress", "report_date": "Date",
        "interrupted": "Interrompu par l'utilisateur (Ctrl+C)",
        "state_saved": "Progres sauvegarde. Utiliser --resume pour continuer.",
        "report_saved": "Rapport sauvegarde.",
        "resume_hint": "Relancer avec --resume pour continuer.",
        "total_time": "Temps total",
        "dry_run_header": "DRY RUN — DICTIONNAIRE UNIQUEMENT", "dry_run_saved": "Dictionnaire sauvegarde",
        "max_passwords": "Max mots de passe (0=illimite)", "stat_max": "Limite max", "stat_unlimited": "illimite",
        "found_skip": "Utilisateurs restants ignores",
    },

    "ru": {
        "banner_title": "Tester parolej WordPress", "banner_auth": "Tolko avtorizovannoe ispolzovanie",
        "config": "NASTROJKA", "phase1": "FAZA 1: RAZVEDKA", "phase2": "FAZA 2: STRATEGIYA",
        "phase3": "FAZA 3: SLOVAR", "phase4": "FAZA 4: ATAKA", "phase5": "FAZA 5: OTCHET",
        "found_header": "NAJDENNYE PAROLI",
        "target_url": "Celevoj URL", "usernames": "Imena polzovatelej (cherez zapyatuyu, pusto=avto)",
        "company_name": "Nazvanie kompanii (dlya slovarya, pusto=propustit)",
        "extra_keywords": "Dopolnitelnye slova (cherez zapyatuyu, pusto=propustit)",
        "crawl_site": "Izvlech slova s sajta?",
        "extra_wordlist": "Dopolnitelnyj slovar (pusto=propustit)",
        "proxy_file": "Fajl spiska proksi (pusto=propustit)", "output_dir": "Katalog vyvoda",
        "start_confirm": "Nachat ataku?", "cancelled": "Otmeneno.", "url_required": "URL obyzatelen!",
        "method_title": "Metod ataki",
        "method_auto": "auto    — Avtomaticheski vybrat luchshij metod (rekomendovano)",
        "method_xmlrpc": "xmlrpc  — XML-RPC multicall (bystro, massovyj test, idealno bez WAF)",
        "method_wplogin": "wplogin — wp-login.php POST (medlenno no nadezhno)",
        "method_restapi": "restapi — REST API Basic Auth (medlenno, trebuet Application Passwords)",
        "batch_title": "Razmer paketa (parolej na zapros)",
        "batch_10": "10  — Ochen medlenno no bezopasno", "batch_25": "25  — Sbalansirovano",
        "batch_50": "50  — Bystro, rekomendovano bez WAF (po umolchaniyu)",
        "batch_100": "100 — Ochen bystro no riskovanno", "batch_200": "200 — Agressivno, tolko s proksi",
        "delay_title": "Zaderzhka mezhdu zaprosami",
        "delay_05": "0.5s — Ochen bystro, ochen vysokij risk", "delay_1": "1s   — Bystro",
        "delay_2": "2s   — Sbalansirovano", "delay_3": "3s   — Bezopasno (po umolchaniyu)",
        "delay_5": "5s   — Ochen bezopasno", "delay_10": "10s  — Ultra bezopasno",
        "risk_high": "Vysokij profil riska — vysokaya veroyatnost bana!",
        "risk_high_tip": "Sovet: dobavte proksi ili uvelichte zaderzhku",
        "risk_medium": "Srednij profil riska", "risk_low": "Nizkij profil riska",
        "risk_label": "Risk", "risk_low_label": "nizkij", "risk_medium_label": "srednij", "risk_high_label": "vysokij",
        "stat_target": "Cel", "stat_user": "Polzovatel", "stat_company": "Kompaniya", "stat_method": "Metod",
        "stat_batch": "Paket", "stat_delay": "Zaderzhka", "stat_proxy": "Proksi",
        "stat_pwd_per_req": "par/zap", "stat_none": "net", "stat_auto": "avto-obnaruzhenie",
        "scanning": "Skanirovanie celi...", "scan_wp": "WordPress", "scan_login": "URL vhoda",
        "scan_xmlrpc": "XML-RPC", "scan_captcha": "CAPTCHA", "scan_waf": "WAF",
        "scan_users": "Polzovateli", "scan_plugins": "Plaginy",
        "scan_active": "AKTIVEN", "scan_methods": "metodov", "scan_disabled": "OTKLYUCHEN",
        "scan_yes": "DA", "scan_no": "NET", "scan_not_found": "ne najden",
        "scan_new_user": "Novyj polzovatel obnaruzhen",
        "generating": "Generaciya parolej...", "generated": "parolej sgenerivano",
        "users_label": "Polzovateli",
        "all_tried": "Vse paroli uzhe provereny", "passwords": "parolej", "batches": "paketov",
        "candidate": "Kandidat", "verifying": "proverka...", "false_positive": "Lozhno polozhitelnyj",
        "not_found": "ne najden", "attempts": "popytok",
        "banned_proxy": "Smena proksi", "remaining": "ostalos",
        "all_proxies_banned": "Vse proksi zablokirovany!",
        "ip_banned": "IP ZABLOKIROVAN! Smenite VPN i ispolzujte --resume",
        "connection_lost": "Soedinenie poteryano", "waiting": "ozhidanie", "ban_detected": "Ban obnaruzhen",
        "total_tried": "Vsego provereno", "total_generated": "Vsego sgenerivano", "found_count": "Najdeno",
        "http_requests": "HTTP-zaprosov", "blocks": "Blokirovok", "ban_count": "Banov",
        "no_password": "Parol ne najden — no nezblokirovannaya ataka sama po sebe uyazvimost",
        "report_at": "Otchet", "log_at": "Log",
        "password_found": "PAROL NAJDEN!", "no_user": "Polzovatel ne najden! Ispolzujte -U.",
        "lang_select": "Language / Yazyk", "lang_en": "English", "lang_tr": "Türkçe",
        "strategy_xmlrpc": "XML-RPC multicall — samyj bystryj metod",
        "strategy_wplogin": "wp-login.php POST", "strategy_restapi": "REST API Basic Auth",
        "strategy_captcha_switch": "CAPTCHA obnaruzhen! Pereklyuchenie na XML-RPC",
        "report_user": "Polzovatel", "report_password": "Parol", "report_time": "Vremya",
        "report_title": "Otchet WordPress Brute Force", "report_date": "Data",
        "interrupted": "Prervano polzovatelem (Ctrl+C)",
        "state_saved": "Progress sohranyon. Ispolzujte --resume dlya prodolzheniya.",
        "report_saved": "Otchet sohranyon.",
        "resume_hint": "Zapustite snova s --resume dlya prodolzheniya.",
        "total_time": "Obshchee vremya",
        "dry_run_header": "DRY RUN — TOLKO SLOVAR", "dry_run_saved": "Slovar sohranyon",
        "max_passwords": "Maks parolej (0=bez ogranichenij)", "stat_max": "Maks limit", "stat_unlimited": "bez ogranichenij",
        "found_skip": "Propusk ostavshihsya polzovatelej",
    },

    "zh": {
        "banner_title": "WordPress mima ceshi gongju", "banner_auth": "Jin shouquan shiyong",
        "config": "PEIZHI", "phase1": "JIEDUAN 1: ZHENCHA", "phase2": "JIEDUAN 2: CELUE",
        "phase3": "JIEDUAN 3: CIDAN", "phase4": "JIEDUAN 4: GONGJI", "phase5": "JIEDUAN 5: BAOGAO",
        "found_header": "YIZHAO MIMA",
        "target_url": "Mubiao URL", "usernames": "Yonghuming (douhao fenkai, kong=zidong)",
        "company_name": "Gongsi mingcheng (yong yu cidan, kong=tiaoguo)",
        "extra_keywords": "Ewai guanjianzi (douhao fenkai, kong=tiaoguo)",
        "crawl_site": "Cong wangzhan tiqu ciyu?",
        "extra_wordlist": "Ewai cidan wenjian (kong=tiaoguo)",
        "proxy_file": "Daili liebiao wenjian (kong=tiaoguo)", "output_dir": "Shuchu mulu",
        "start_confirm": "Kaishi gongji?", "cancelled": "Yiquxiao.", "url_required": "URL shi bixude!",
        "method_title": "Gongji fangfa",
        "method_auto": "auto    — Zidong xuanze zuijia fangfa (tuijian)",
        "method_xmlrpc": "xmlrpc  — XML-RPC multicall (kuaisu, piliang ceshi)",
        "method_wplogin": "wplogin — wp-login.php POST (man dan kekao)",
        "method_restapi": "restapi — REST API Basic Auth (man, xuyao Application Passwords)",
        "scanning": "Zhengzai saomiao mubiao...", "generating": "Zhengzai shengcheng mima...",
        "generated": "ge mima yi shengcheng", "passwords": "ge mima", "batches": "ge pi",
        "password_found": "MIMA YIZHAO!", "not_found": "wei zhaodao", "attempts": "ci changshi",
        "total_tried": "Zong ceshi", "total_generated": "Zong shengcheng", "found_count": "Yizhao",
        "total_time": "Zong shijian", "report_at": "Baogao", "log_at": "Rizhi",
        "interrupted": "Yonghu zhongduan (Ctrl+C)", "state_saved": "Jindu yi baocun.",
        "lang_select": "Language / Yuyan", "lang_en": "English", "lang_tr": "Türkçe",
        "risk_label": "Fengxian", "risk_low_label": "di", "risk_medium_label": "zhong", "risk_high_label": "gao",
        "stat_target": "Mubiao", "stat_user": "Yonghu", "stat_method": "Fangfa",
        "scan_active": "HUOYUE", "scan_disabled": "JINYONG", "scan_yes": "SHI", "scan_no": "FOU",
    },

    "pt": {
        "banner_title": "Testador de Senhas WordPress", "banner_auth": "Apenas Uso Autorizado",
        "config": "CONFIGURACAO", "phase1": "FASE 1: RECONHECIMENTO", "phase2": "FASE 2: ESTRATEGIA",
        "phase3": "FASE 3: DICIONARIO", "phase4": "FASE 4: ATAQUE", "phase5": "FASE 5: RELATORIO",
        "found_header": "SENHAS ENCONTRADAS",
        "target_url": "URL alvo", "usernames": "Usuarios (separados por virgula, vazio=auto)",
        "company_name": "Nome da empresa (para dicionario, vazio=pular)",
        "extra_keywords": "Palavras-chave extras (separadas por virgula, vazio=pular)",
        "crawl_site": "Extrair palavras do site?",
        "start_confirm": "Iniciar ataque?", "cancelled": "Cancelado.", "url_required": "URL e obrigatoria!",
        "method_title": "Metodo de ataque",
        "method_auto": "auto    — Selecionar melhor metodo automaticamente (recomendado)",
        "method_xmlrpc": "xmlrpc  — XML-RPC multicall (rapido, teste em massa)",
        "method_wplogin": "wplogin — wp-login.php POST (lento mas confiavel)",
        "method_restapi": "restapi — REST API Basic Auth (lento)",
        "scanning": "Escaneando alvo...", "generating": "Gerando senhas...",
        "generated": "senhas geradas", "passwords": "senhas", "batches": "lotes",
        "password_found": "SENHA ENCONTRADA!", "not_found": "nao encontrada", "attempts": "tentativas",
        "total_tried": "Total testadas", "total_generated": "Total geradas", "found_count": "Encontradas",
        "total_time": "Tempo total", "report_at": "Relatorio", "log_at": "Log",
        "interrupted": "Interrompido pelo usuario (Ctrl+C)", "state_saved": "Progresso salvo.",
        "lang_select": "Language / Idioma", "lang_en": "English", "lang_tr": "Türkçe",
        "risk_label": "Risco", "risk_low_label": "baixo", "risk_medium_label": "medio", "risk_high_label": "alto",
        "stat_target": "Alvo", "stat_user": "Usuario", "stat_method": "Metodo",
        "scan_active": "ATIVO", "scan_disabled": "DESATIVADO", "scan_yes": "SIM", "scan_no": "NAO",
    },

    "ja": {
        "banner_title": "WordPress pasuwado tesuto tsuru", "banner_auth": "Kengen ari no shiyou nomi",
        "config": "SETTEI", "phase1": "FAZE 1: CHOSA", "phase2": "FAZE 2: SENRYAKU",
        "phase3": "FAZE 3: JISHO", "phase4": "FAZE 4: KOGEKI", "phase5": "FAZE 5: REPOTO",
        "found_header": "HAKKEN SARETA PASUWADO",
        "target_url": "Tagetto URL", "usernames": "Yuza mei (kanma kuugiri, kara=jidou)",
        "start_confirm": "Kogeki wo kaishi shimasuka?", "cancelled": "Kyanseru.", "url_required": "URL ga hitsuyou!",
        "scanning": "Tagetto wo sukyan chu...", "generating": "Pasuwado wo seisei chu...",
        "generated": "ko no pasuwado seisei", "passwords": "pasuwado", "batches": "batchi",
        "password_found": "PASUWADO HAKKEN!", "not_found": "mitsukaranai", "attempts": "kai no kokoromi",
        "total_tried": "Gokei tesuto", "total_generated": "Gokei seisei", "found_count": "Hakken",
        "total_time": "Gokei jikan", "report_at": "Repoto", "log_at": "Rogu",
        "interrupted": "Yuza ni yori chudan (Ctrl+C)", "state_saved": "Shinchoku hozon zumi.",
        "lang_select": "Language / Gengo", "lang_en": "English", "lang_tr": "Türkçe",
        "risk_label": "Risuku", "risk_low_label": "tei", "risk_medium_label": "chu", "risk_high_label": "kou",
        "stat_target": "Tagetto", "stat_user": "Yuza", "stat_method": "Houhou",
        "scan_active": "YUUKOU", "scan_disabled": "MUKOU", "scan_yes": "HAI", "scan_no": "IIE",
    },

    "ar": {
        "banner_title": "Adat ikhtbar kalimat murur WordPress", "banner_auth": "Lil-istikhdam al-musarrah bihi faqat",
        "config": "AL-I'DAD", "phase1": "MARHALA 1: AL-ISTIKSHAF", "phase2": "MARHALA 2: AL-ISTRATIJIYA",
        "phase3": "MARHALA 3: QAMUS", "phase4": "MARHALA 4: AL-HUJUM", "phase5": "MARHALA 5: AL-TAQRIR",
        "found_header": "KALIMAT AL-MURUR AL-MUKTASHAFA",
        "target_url": "URL al-hadaf", "usernames": "Asma al-mustakhdimin (fasil, farigh=talkha'i)",
        "start_confirm": "Bada al-hujum?", "cancelled": "Mulgha.", "url_required": "URL matlub!",
        "scanning": "Jari maseh al-hadaf...", "generating": "Jari tawlid kalimat al-murur...",
        "generated": "kalimat murur tamma tawliduha", "passwords": "kalimat murur", "batches": "mujmu'at",
        "password_found": "KALIMAT AL-MURUR MUKTASHAFA!", "not_found": "lam yutam al-'uthur", "attempts": "muhawalat",
        "total_tried": "Ijmali al-ikhtbarat", "total_generated": "Ijmali al-muwalada", "found_count": "Muktashaf",
        "total_time": "Al-waqt al-ijmali", "report_at": "Taqrir", "log_at": "Sijil",
        "interrupted": "Tamma al-muqata'a (Ctrl+C)", "state_saved": "Tamma hifz al-taqaddum.",
        "lang_select": "Language / Al-lugha", "lang_en": "English", "lang_tr": "Türkçe",
        "risk_label": "Al-mukhatra", "risk_low_label": "munkhafid", "risk_medium_label": "mutawasit", "risk_high_label": "murtafi'",
        "stat_target": "Al-hadaf", "stat_user": "Al-mustakhdim", "stat_method": "Al-tariqa",
        "scan_active": "NASHIT", "scan_disabled": "MU'ATTAL", "scan_yes": "NA'AM", "scan_no": "LA",
    },
}


def set_lang(code):
    global LANG
    if code in STRINGS:
        LANG = code


def t(key):
    """Translation function"""
    return STRINGS.get(LANG, STRINGS["en"]).get(key, STRINGS["en"].get(key, key))
